config/routes.rb
Rails.application.routes.draw do
  # le GET articles va executer l action de index dans le ArticlesController
  # get '/articles', to: 'articles#index'
  # get '/articles/:id', to: 'articles#show'
  # La ressource permet de creer les routes pour le CRUD sur ce controller
  # Chose qu'on a fait manuellement au dessus avec le index(get) et show
  resources :articles do
    resources :comments
  end
  resources :categories
  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  # Relations
  belongs_to :category, counter_cache: true
  has_many :comments
  has_and_belongs_to_many :tags
  # Relation polymorphic
  has_many :pictures, as: :imageable

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 10 }

  # Filtres
  # scope par defaut
  default_scope { order(created_at: :asc) }

  # sorte de filtre dispo que l'on cree
  scope :published, -> { where(online: true) }
  # scope avec parametre
  scope :online, ->(param) { where(online: param) }
  # scope avec un bloc
  scope :onlineVerif, lambda { |param|
    where(online: param) if param.to_b?
  }

  # methode de classe comme un scope
  # attention cette methode peut renvoyer null
  # et donc renvoyer une erreur
  def self.offline
    where(online: false)
  end
end

app/models/categorie.rb
class Categorie < ApplicationRecord
  validates :name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
  validates :name, presence: true
  # Relation polymorphic
  has_many :pictures, as: :imageable
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
  to_belongs :imageable, polymorphic: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    # utilisation avec un scope de Article ( du model )
    @articles = Article.published.all
    # exemple avec un parametre
    # @articles = Article.online(true).all
    # exemple si on veut que d'office on prend la categorie liée
    # Permet de ne pas faire de requete supplementaire
    # il recuperera les categories et tags associé a chaque article
    # @articles = Article.includes(:category, :tags).all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params

    if @article.save
      flash[:success] = 'Article créé avec succès'
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update article_params
      flash[:success] = 'Article mis à jour avec succès'
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  # Permet de valider les parametres
  def article_params
    params.require(:article).permit(:title, :body, :online)
  end

  # Permet d eviter de repeter cette ligne, on va l utiliser dans le before_action
  def set_article
    @article = Article.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:success] = 'Categorie créé avec succès'
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] = 'Categorie mis à jour avec succès'
      redirect_to categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    flash[:success] = 'Categorie supprimée avec succès'
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find params[:article_id]
    @comment = @article.comments.create comment_params
    redirect_to article_path @article
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class='card mb-2'>
  <div class="card-body">
    <% if article.category %>
      <span class="badge rounded-pill text-bg-info mb-2"><%= article.category.name %></span>
    <% end %>
    <% article.tags.each do |tag| %>
      <span class="badge rounded-pill text-bg-secondary mb-2"><%= tag.name %></span>
    <% end %>
    <h3 class="card-title">
      <%= link_to article.title, article %>
    </h3>
    <p> class="card-text"><%= article.body %> </p>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<div>
  <%= form.label :title, 'Titre', class: 'form-label' %><br>
  <%= form.text_field :title, class: 'form-control' %>
  <% article.errors.full_messages_for(:title).each do |message| %>
    <div class='text-danger'><%= message %></div>
  <% end %>
</div>

<div class='mt-2'>
  <%= form.label :body, 'Contenu', class: 'form-label' %><br>
  <%= form.text_area :body, class: 'form-control' %>
  <% article.errors.full_messages_for(:body).each do |message| %>
    <div class='text-danger'><%= message %></div>
  <% end %>
</div>
<div class='mt-2'>
  <%= form.label :online, 'Publié', class: 'form-label mx-2' %>
  <%= form.check_box :online %>
  <% article.errors.full_messages_for(:online).each do |message| %>
    <div class='text-danger'><%= message %></div>
  <% end %>
</div>
<div class="mt-4">
  <%= form.submit class: 'btn btn-success'%>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Liste des articles</h1>
<%= link_to "Ajouter un article", new_article_path, class: "btn btn-success mb-2" %>
  <% @articles.each do |article|%>
    <%= render article %>
  <% end %>

app/views/articles/new.html.erb
<h1>Nouveau article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<%= link_to "Edit", edit_article_path(@article), class: 'btn btn-primary' %></li>
<%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" }, class: 'btn btn-danger' %>

<% if !@article.comments.empty? %>
  <h4 class='mt-3'>Commentaires</h4>
  <%= render @article.comments %>
<% end %>

<h4 class='mt-3'>Ajouter un commentaire</h4>
<%= render 'comments/form' %>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
<div class='mb2'>
  <%= form.label :name, 'Nom', class: 'form-label' %><br>
  <%= form.text_field :name, class: 'form-control' %>
  <% category.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

<div class="mt-4">
  <%= form.submit class: 'btn btn-success'%>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editer la catégorie</h1>
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h1>Liste des categories</h1>
<%= link_to 'Ajouter une catégorie', new_category_path, class:'btn btn-success' %>
<table class='table'>
  <thead>
    <tr>
<td>Id</td>
<td>Nom</td>
<td>Actions</td>
    </tr>

  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
<td><%= category.id %></td>
<td><%= category.name %></td>
<td><%= link_to 'Editer', edit_category_path(category), class: 'btn btn-primary'%>
<%= link_to 'Supprimer', category_path(category), data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr?'}, class: 'btn btn-danger'%>
</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>
<%= render "form", category: @category %>

app/views/comments/_comment.html.erb
<div class="card mb-2">
  <div class="card-body">
    <span class="fw-bold">
      <%= comment.commenter %> :
    </span>
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build] do |form| %>
  <div class="mb-2">
    <%= form.text_field :commenter, class: 'form-control', placeholder: 'Pseudo' %>
   </div>
  <div class="mb-2">
    <%= form.text_area :body, class: 'form-control', placeholder: 'Que voulez-vous dire?' %>
  </div>
<%= form.submit class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="border-bottom ">
      <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid">
          <a class="navbar-brand " href="<%= root_path %>">Rails</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="true"  href="<%= root_path %>">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="<%= articles_path %>">Articles</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="<%= categories_path %>">Categories</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="m-3">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome</h1>
<p>Juste a tiny website with Rails for the training</p>